### ISSUE TITLE
JSON/RESTful API

### ISSUE THREAD

**Issue by TobiTenno** [weblue/weblue.github.io#22]
Would be fantastic to get the data out to people via bots (like genesis)

**Comment by weblue** [comment]
A restful API would be awesome, however the database tier that's currently being paid for (at a clean $0), only supports up to 100 concurrent connections, which the tierlist was able to reach upon reddit posts.
I'll take a look at the viability of a throttled API. If the Patreon ends up generating around $5 a month, I'll match it and upgrade to allow for 1k concurrent connections. Also, if the traffic of the website somehow manages to hit 100 concurrent through organic growth before the Patreon generates enough cashflow, I'll just cover the upgrade myself.

**Comment by TobiTenno** [comment]
Something you might think about is storing it in flatfiles loaded from github, that way you don't have to worry about db connections. we do something similar on https://drops.warframestat.us.
It runs on github pages still, but we shove it behind cloudflare for https and have flatfiles there, making easier access for outside fetching, like i do with genesis.

**Comment by weblue** [comment]
Currently, the backend uses Firebase, but FlatFiles is interesting. Do you just use commits to handle editing the supporting "database"?

**Comment by TobiTenno** [comment]
yup, our examples are a little idealistic, because they're auto-updated whenever the json updated and automatically committed, but yeah, we just use commits to handle editing the files themselves, and since the site just pulls whatever's there, it doesn't matter if it's out of date or if you're mid-update, you can commit partially or continue as you like, as you'd do with normal database commits

**Comment by weblue** [comment]
I'm at work right now, but if you could contact me on Discord or some other means, I'd like to have a deeper discussion. I think moving the JSONs to Github pages is certainly viable considering the scope of this project, however the only hurdle to get over is the JSON editor that was planned in the future.

If there's a method to tailor a JSON editor with committing functionality, there would be 0 problems creating an emulated API. I've been using firebase since their editor is easy enough to use without having to write an actual JSON

**Comment by TobiTenno** [comment]
i mean, worst comes to worst, you could have people copy the json into http://jsoneditoronline.org/ and then back when done, but yeah, let's talk on discord. feel free to find me on https://discord.gg/warframe, i'm one of the admins

**Comment by weblue** [comment]
Migrated database from Firebase to a static json backend. More API endpoints may be created in the future.

TODO: document the API

Current endpoint: weblue.github.io/js/thelist.json
