### ISSUE TITLE
Vanilla gammacor not listed

### ISSUE THREAD

**Issue by AUTplayed** [weblue/weblue.github.io#27]
Hi, I noticed that the Synoid Gammacor is listed but it doesn't have a note for the vanilla variant.

**Comment by sakai4eva** [comment]
Issue closed. 

Also, Synoid Gammacor is way, waay, waaaaaaaayyy better so why waste time on a weapon variant that is inferior?

**Comment by AUTplayed** [comment]
sorry for nitpicking, but you got a typo in there. And yes, it's way better, but if it's not listed a new player wouldn't know :)
