### ISSUE TITLE
Enforce HTTPS with GitHub Pages site

### ISSUE THREAD

**Issue by CorruptComputer** [weblue/weblue.github.io#30]
This would greatly increase security, with no downside. It is an option in the settings for GitHub Pages and I use it for [my site](https://github.com/CorruptComputer/CorruptComputer.GitHub.io) with no issues or hassles involved. Its as simple as checking a box and waiting for the DNS records to update.
Here is the option you need under the settings for the repository:
![screenshot from 2018-07-31 13-37-46](https://user-images.githubusercontent.com/5573038/43480134-efde6440-94c7-11e8-93c7-d04405cb4e86.png)

**Comment by weblue** [comment]
I did it my guy
